language: node_js

node_js:
  - 18
  - 19
  - 20

notifications:
  email: false

install:
  - SKIP_SETUP=true npm install

script:
  - npm run lint:styles
  - npm run lint:js
  - npm run build

dist: trusty
sudo: false
